### ISSUE TITLE
希望支持自定义外链域名

### ISSUE THREAD

**Issue by cuncle** [layerssss/manager-for-upyun#10]
目前是获取 <bucket>.b0.upaiyun.com 的形式。希望可以自定义这个字段，自定义域名。

**Comment by breeze-yang** [comment]
这个非常的有用，希望能支持这个功能。感谢

**Comment by Momo707577045** [comment]
+1

**Comment by Rabbit2108** [comment]
+1

**Comment by layerssss** [comment]
https://github.com/layerssss/manager-for-upyun/releases/tag/v0.0.9

自定义外链域名的功能刚发布了。

6bc12d86e8e5fa5f267183878bad2cee80728dbb

**Comment by Rabbit2108** [comment]
> https://github.com/layerssss/manager-for-upyun/releases/tag/v0.0.9
> 
> 自定义外链域名的功能刚发布了。
> 
> [6bc12d8](https://github.com/layerssss/manager-for-upyun/commit/6bc12d86e8e5fa5f267183878bad2cee80728dbb)
编辑器打开出错了
https://ae01.alicdn.com/kf/H5f41056f49f3479da9c84ef931f583c7G.jpg
