### ISSUE TITLE
作者你好，现在接口升级了吗，没法登录了

### ISSUE THREAD

**Issue by Panway** [layerssss/manager-for-upyun#12]
操作失败:{"msg":"need bucket name","code":40000003,"id":"080ef45fd798cee8f285c56e8047c686"}

**Comment by ZhaiHaiSheng** [comment]
作者您好, 我可以登录进去看到文件, 但是点击文件就会出现报错.
{"code":"40510004","msg":"invisible domain"}

**Comment by layerssss** [comment]
自定域名支持发布了 https://github.com/layerssss/manager-for-upyun/releases/tag/v0.0.9 @ZhaiHaiSheng
