### ISSUE TITLE
请教正确编译的姿势～

### ISSUE THREAD

**Issue by zdy23216340** [layerssss/manager-for-upyun#6]
您好，clone了您的项目，然后运行build.sh，执行完后找不到zip包，不知道哪里出错了呢～

**Comment by layerssss** [comment]
你成功编译了吗？成功编译了的话再关 issue 吧，这个东西很久没管了，记得的东西不多了

**Comment by zdy23216340** [comment]
不好意思。。 notice太多了，今天整理的时候才看到。。。

**Comment by layerssss** [comment]
没事，有问题留言

Cheers,
Michael
