### ISSUE TITLE
无法下载工具

### ISSUE THREAD

**Issue by kucy** [layerssss/manager-for-upyun#7]
http://micyin.b0.upaiyun.com/manager-for-upyun/manager-for-upyun-0.0.6-win32.exe       405错误

**Comment by layerssss** [comment]
@kucy 感谢提醒，应该是因为之前托管的又拍云账号过期了，我找个时间移植到 Electron 后再重新编译一下再通知你。

**Comment by layerssss** [comment]
我现在没有又拍云的账号了，你能提供一组测试用的账号给我吗？（记得之前又拍可以创建一组独立的用户名密码，然后建立一个专有的空间），如果可以的话，请发到我邮箱里 layerssss@gmail.com 谢谢

**Comment by layerssss** [comment]
@kucy  Hi， 下载版本发布了： https://github.com/layerssss/manager-for-upyun/releases

**Comment by kucy** [comment]
嗯嗯。谢谢
